package com.example.xiaoying.model;

public class Note {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.id
     *
     * @mbg.generated Sun Apr 19 15:40:50 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.video_id
     *
     * @mbg.generated Sun Apr 19 15:40:50 CST 2020
     */
    private Long videoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.title
     *
     * @mbg.generated Sun Apr 19 15:40:50 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.content
     *
     * @mbg.generated Sun Apr 19 15:40:50 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.gmt_create
     *
     * @mbg.generated Sun Apr 19 15:40:50 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.gmt_modified
     *
     * @mbg.generated Sun Apr 19 15:40:50 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.creator
     *
     * @mbg.generated Sun Apr 19 15:40:50 CST 2020
     */
    private Long creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.id
     *
     * @return the value of note.id
     *
     * @mbg.generated Sun Apr 19 15:40:50 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.id
     *
     * @param id the value for note.id
     *
     * @mbg.generated Sun Apr 19 15:40:50 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.video_id
     *
     * @return the value of note.video_id
     *
     * @mbg.generated Sun Apr 19 15:40:50 CST 2020
     */
    public Long getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.video_id
     *
     * @param videoId the value for note.video_id
     *
     * @mbg.generated Sun Apr 19 15:40:50 CST 2020
     */
    public void setVideoId(Long videoId) {
        this.videoId = videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.title
     *
     * @return the value of note.title
     *
     * @mbg.generated Sun Apr 19 15:40:50 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.title
     *
     * @param title the value for note.title
     *
     * @mbg.generated Sun Apr 19 15:40:50 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.content
     *
     * @return the value of note.content
     *
     * @mbg.generated Sun Apr 19 15:40:50 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.content
     *
     * @param content the value for note.content
     *
     * @mbg.generated Sun Apr 19 15:40:50 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.gmt_create
     *
     * @return the value of note.gmt_create
     *
     * @mbg.generated Sun Apr 19 15:40:50 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.gmt_create
     *
     * @param gmtCreate the value for note.gmt_create
     *
     * @mbg.generated Sun Apr 19 15:40:50 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.gmt_modified
     *
     * @return the value of note.gmt_modified
     *
     * @mbg.generated Sun Apr 19 15:40:50 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.gmt_modified
     *
     * @param gmtModified the value for note.gmt_modified
     *
     * @mbg.generated Sun Apr 19 15:40:50 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.creator
     *
     * @return the value of note.creator
     *
     * @mbg.generated Sun Apr 19 15:40:50 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.creator
     *
     * @param creator the value for note.creator
     *
     * @mbg.generated Sun Apr 19 15:40:50 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }
}